In [1]:
import numpy as np
import pandas as pd

In [2]:
import pycaret

In [3]:
df = pd.read_csv ('https://raw.githubusercontent.com/pycaret/datasets/main/data/common/house.csv')
df
pd.set_option('display.max_columns', None)
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,5,1999,2000,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,PConc,Gd,TA,No,Unf,0,Unf,0,953,953,GasA,Ex,Y,SBrkr,953,694,0,1647,0,0,2,1,3,1,TA,7,Typ,1,TA,Attchd,1999.0,RFn,2,460,TA,TA,Y,0,40,0,0,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,6,6,1978,1988,Gable,CompShg,Plywood,Plywood,Stone,119.0,TA,TA,CBlock,Gd,TA,No,ALQ,790,Rec,163,589,1542,GasA,TA,Y,SBrkr,2073,0,0,2073,1,0,2,0,3,1,TA,7,Min1,2,TA,Attchd,1978.0,Unf,2,500,TA,TA,Y,349,0,0,0,0,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,9,1941,2006,Gable,CompShg,CemntBd,CmentBd,None,0.0,Ex,Gd,Stone,TA,Gd,No,GLQ,275,Unf,0,877,1152,GasA,Ex,Y,SBrkr,1188,1152,0,2340,0,0,2,0,4,1,Gd,9,Typ,2,Gd,Attchd,1941.0,RFn,1,252,TA,TA,Y,0,60,0,0,0,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,6,1950,1996,Hip,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,TA,TA,Mn,GLQ,49,Rec,1029,0,1078,GasA,Gd,Y,FuseA,1078,0,0,1078,1,0,1,0,2,1,Gd,5,Typ,0,NaN,Attchd,1950.0,Unf,1,240,TA,TA,Y,366,0,112,0,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,5,6,1965,1965,Gable,CompShg,HdBoard,HdBoard,None,0.0,Gd,TA,CBlock,TA,TA,No,BLQ,830,LwQ,290,136,1256,GasA,Gd,Y,SBrkr,1256,0,0,1256,1,0,1,1,3,1,TA,6,Typ,0,NaN,Attchd,1965.0,Fin,1,276,TA,TA,Y,736,68,0,0,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [4]:
df.shape

(1460, 81)

In [5]:
df.to_csv('./RegressionData/House2.csv', index=False)

In [6]:
## Remove unseen samples

data = df.sample(frac=0.95,random_state=28)
data_unseen = df.drop(data.index)

print(f'Data for model: {data.shape},\nData for unseen predictions: { data_unseen.shape}')

Data for model: (1387, 81),
Data for unseen predictions: (73, 81)

In [7]:
from pycaret.regression import *
reg = setup(data = data, target='SalePrice', normalize=True, session_id=42)

In [8]:
from pycaret.regression import *
setup(data = data, target='SalePrice', normalize=True, session_id=42)

In [9]:
df.isna().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [10]:
compare_models()

Initiated  . . . . . . . . . . . . . . . . . .           19:16:06
Status     . . . . . . . . . . . . . . . . . .  Loading Estimator
Estimator  . . . . . . . . . . . . . . . . . .  Linear Regression

In [11]:
gbr = create_model('gbr')

Initiated  . . . . . . . . . . . . . . . . . .                     19:21:21
Status     . . . . . . . . . . . . . . . . . .             Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Gradient Boosting Regressor

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [12]:
lightgbm = create_model('lightgbm')

,,
,,
Initiated,. . . . . . . . . . . . . . . . . .,19:21:33
Status,. . . . . . . . . . . . . . . . . .,Fitting 10 Folds
Estimator,. . . . . . . . . . . . . . . . . .,Light Gradient Boosting Machine

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [13]:
predict_model(gbr)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,prediction_label
770,771,85,RL,NaN,7252,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,4,2009,WD,Normal,134900,127222.838971
14,15,20,RL,NaN,10920,Pave,NaN,IR1,Lvl,AllPub,...,NaN,GdWo,NaN,0,5,2008,WD,Normal,157000,146635.876076
1090,1091,90,RL,60.0,8544,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2009,WD,Normal,92900,90467.844745
870,871,20,RL,60.0,6600,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,8,2009,WD,Normal,109500,100998.372819
1336,1337,90,RL,87.0,9246,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,11,2008,WD,Normal,135000,139788.620741
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,229,20,RL,70.0,8521,Pave,NaN,Reg,Lvl,AllPub,...,NaN,MnPrv,NaN,0,5,2010,WD,Normal,125000,121642.259647
931,932,20,RL,70.0,9100,Pave,NaN,Reg,Lvl,AllPub,...,NaN,GdWo,NaN,0,7,2009,WD,Normal,117500,126641.689529
699,700,120,FV,59.0,4282,Pave,Pave,IR2,Lvl,AllPub,...,NaN,NaN,NaN,0,7,2008,WD,Normal,196000,188340.732160
1350,1351,90,RL,91.0,11643,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,8,2009,WD,Normal,200000,176614.985697
738,739,90,RL,60.0,10800,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,3,2009,WD,Alloca,179000,144171.692120

In [14]:
## default is 10 folds but we can make it 15 folds... for improved fitting

In [15]:
gbr_tuned_model = tune_model(gbr)

Initiated  . . . . . . . . . . . . . . . . . .                     19:21:42
Status     . . . . . . . . . . . . . . . . . .    Searching Hyperparameters
Estimator  . . . . . . . . . . . . . . . . . .  Gradient Boosting Regressor

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [16]:
tuned_model = tune_model(gbr)

Initiated  . . . . . . . . . . . . . . . . . .                     19:23:56
Status     . . . . . . . . . . . . . . . . . .    Searching Hyperparameters
Estimator  . . . . . . . . . . . . . . . . . .  Gradient Boosting Regressor

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [17]:
print(tuned_model)

GradientBoostingRegressor(learning_rate=0.05, max_depth=6, max_features='sqrt',
                          min_impurity_decrease=0.3, min_samples_leaf=4,
                          min_samples_split=10, n_estimators=270,
                          random_state=42, subsample=0.7)

In [18]:
final_model = finalize_model(tuned_model)
final_model

Pipeline(memory=FastMemory(location=C:\Users\juud0\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(include=['Id', 'MSSubClass', 'LotFrontage',
                                             'LotArea', 'OverallQual',
                                             'OverallCond', 'YearBuilt',
                                             'YearRemodAdd', 'MasVnrArea',
                                             'BsmtFinSF1', 'BsmtFinSF2',
                                             'BsmtUnfSF', 'TotalBsmtSF',
                                             '1stFlrSF', '2ndFlrSF',
                                             'LowQualFinSF', 'GrLivArea',
                                             'Bsmt...
                                                                    'Functional',
                                                                    'FireplaceQu', ...],
                                                              handle_missing='return_nan',
                                                              use_cat_names=True))),
                ('normalize', TransformerWrapper(transformer=StandardScaler())),
                ('actual_estimator',
                 GradientBoostingRegressor(learning_rate=0.05, max_depth=6,
                                           max_features='sqrt',
                                           min_impurity_decrease=0.3,
                                           min_samples_leaf=4,
                                           min_samples_split=10,
                                           n_estimators=270, random_state=42,
                                           subsample=0.7))])

In [19]:
save_model(final_model, './models/house2_gbr')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=C:\Users\juud0\AppData\Local\Temp\joblib),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['Id', 'MSSubClass', 'LotFrontage',
                                              'LotArea', 'OverallQual',
                                              'OverallCond', 'YearBuilt',
                                              'YearRemodAdd', 'MasVnrArea',
                                              'BsmtFinSF1', 'BsmtFinSF2',
                                              'BsmtUnfSF', 'TotalBsmtSF',
                                              '1stFlrSF', '2ndFlrSF',
                                              'LowQualFinSF', 'GrLivArea',
                                              'Bsmt...
                                                                     'Functional',
                                                                     'FireplaceQu', ...],
                                                               handle_missing='return_nan',
                                                               use_cat_names=True))),
                 ('normalize', TransformerWrapper(transformer=StandardScaler())),
                 ('actual_estimator',
                  GradientBoostingRegressor(learning_rate=0.05, max_depth=6,
                                            max_features='sqrt',
                                            min_impurity_decrease=0.3,
                                            min_samples_leaf=4,
                                            min_samples_split=10,
                                            n_estimators=270, random_state=42,
                                            subsample=0.7))]),
 './models/house2_gbr.pkl')

In [20]:
## data = [[332.5,	142.5,	0.0,	228.0,	0.0,	932.0,	594.0,	365]]

In [21]:
df[:1:]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500

In [22]:
model_test = load_model('./models/house2_gbr')

Transformation Pipeline and Model Successfully Loaded

In [23]:
##df1 = [[ 1,	2,	20,	RL	,80.0	,9600,	'Pave',	'NaN'	,'Reg'	,'Lvl',	'AllPub','FR2',	'Gtl',	'Veenker'	,'Feedr'	,'Norm',	'1Fam'	,'1Story',	6,	8	,1976	,1976,	'Gable',	'CompShg'	,'MetalSd',	'MetalSd'	,'None'	,0.0,	'TA',	'TA'	,'CBlock',	'Gd',	'TA',	'Gd',	'ALQ',	978,	'Unf',	0,	284	,1262	,'GasA',	'Ex',	'Y'	,'SBrkr'	,1262,	0	,0	,1262,	0,	1,	2,	0,	3,	1,	TA,	6,	'Typ'	,1,	TA	,'Attchd', 
    ##    1976.0,	RFn	2,	460	,TA,	TA	,Y,	298,	0,	0,	0,	0,	0,	NaN,	NaN,	NaN,	0,	5,	2007,	WD	,Normal	]]

In [24]:
#,181500

In [25]:
df_test = [[ 2,	20,	'RL'	,80.0	,9600,	'Pave',	'NaN'	,'Reg'	,'Lvl',	'AllPub','FR2',	'Gtl',	'Veenker'	,'Feedr'	,'Norm',	'1Fam'	,'1Story',	6,	8	,1976	,1976,	'Gable',	'CompShg'	,'MetalSd',	'MetalSd'	,'None'	,0.0,	'TA',	'TA'	,'CBlock',	'Gd',	'TA',	'Gd',	'ALQ',	978,	'Unf',	0,	284	,1262	,'GasA',	'Ex',	'Y'	,'SBrkr'	,1262,	0	,0	,1262,	0,	1,	2,	0,	3,	1,	'TA',	6,	'Typ'	,1,	'TA'	,'Attchd', 
        1976.0,	'RFn',	2,	460, 'TA',	'TA'	,'Y',	298,	0,	0,	0,	0,	0,	'NaN',	'NaN',	'NaN',	0,	5,	2007,	'WD'	,'Normal']]

In [26]:
df_test

[[2,
  20,
  'RL',
  80.0,
  9600,
  'Pave',
  'NaN',
  'Reg',
  'Lvl',
  'AllPub',
  'FR2',
  'Gtl',
  'Veenker',
  'Feedr',
  'Norm',
  '1Fam',
  '1Story',
  6,
  8,
  1976,
  1976,
  'Gable',
  'CompShg',
  'MetalSd',
  'MetalSd',
  'None',
  0.0,
  'TA',
  'TA',
  'CBlock',
  'Gd',
  'TA',
  'Gd',
  'ALQ',
  978,
  'Unf',
  0,
  284,
  1262,
  'GasA',
  'Ex',
  'Y',
  'SBrkr',
  1262,
  0,
  0,
  1262,
  0,
  1,
  2,
  0,
  3,
  1,
  'TA',
  6,
  'Typ',
  1,
  'TA',
  'Attchd',
  1976.0,
  'RFn',
  2,
  460,
  'TA',
  'TA',
  'Y',
  298,
  0,
  0,
  0,
  0,
  0,
  'NaN',
  'NaN',
  'NaN',
  0,
  5,
  2007,
  'WD',
  'Normal']]

In [27]:
df_test
pd.DataFrame(df_test)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal

In [28]:
cols = model_test.feature_names_in_[:-1]
cols

['Id',
 'MSSubClass',
 'MSZoning',
 'LotFrontage',
 'LotArea',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'MasVnrArea',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinSF1',
 'BsmtFinType2',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'KitchenQual',
 'TotRmsAbvGrd',
 'Functional',
 'Fireplaces',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageCars',
 'GarageArea',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleType',
 'SaleCondition']

In [29]:
pd.DataFrame(cols)

                0
0              Id
1      MSSubClass
2        MSZoning
3     LotFrontage
4         LotArea
..            ...
75        MiscVal
76         MoSold
77         YrSold
78       SaleType
79  SaleCondition

[80 rows x 1 columns]

In [30]:
cols = model_test.feature_names_in_[:-1]
test_df = pd.DataFrame(df_test, columns=cols)
prediction = model_test.predict(test_df)[0]
prediction

171700.497386119

In [31]:
act_pred = 181500
act_pred

181500

In [32]:
new_pred = prediction.round(2)
new_pred

171700.5

In [33]:
MAE = act_pred - new_pred
MAE

9799.5

In [34]:
MPAE = MAE/act_pred
MPAE

0.05399173553719008

In [35]:
data_unseen

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
45,46,120,RL,61.0,7658,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2010,WD,Normal,319900
60,61,20,RL,63.0,13072,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,New,Partial,158000
83,84,20,RL,80.0,8892,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2007,COD,Normal,126500
87,88,160,FV,40.0,3951,Pave,Pave,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2009,New,Partial,164500
109,110,20,RL,105.0,11751,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,1,2010,COD,Normal,190000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1284,1285,50,RL,50.0,9638,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,3,2010,WD,Normal,169000
1302,1303,60,RL,92.0,10120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2006,WD,Normal,290000
1308,1309,20,RM,100.0,12000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2008,WD,Normal,147000
1321,1322,20,RL,NaN,6627,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2008,WD,Normal,72500
1431,1432,120,RL,NaN,4928,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,143750

In [36]:
batch = data_unseen.iloc[:,:-1]
batch

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
45,46,120,RL,61.0,7658,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2010,WD,Normal
60,61,20,RL,63.0,13072,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,New,Partial
83,84,20,RL,80.0,8892,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,7,2007,COD,Normal
87,88,160,FV,40.0,3951,Pave,Pave,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2009,New,Partial
109,110,20,RL,105.0,11751,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,1,2010,COD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1284,1285,50,RL,50.0,9638,Pave,NaN,Reg,Lvl,AllPub,...,116,0,NaN,NaN,NaN,0,3,2010,WD,Normal
1302,1303,60,RL,92.0,10120,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2006,WD,Normal
1308,1309,20,RM,100.0,12000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,GdWo,NaN,0,5,2008,WD,Normal
1321,1322,20,RL,NaN,6627,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,7,2008,WD,Normal
1431,1432,120,RL,NaN,4928,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2009,WD,Normal

In [37]:
predictions = model_test.predict(batch)
predictions

array([274907.31042166, 166013.00294679, 127526.38001776, 171233.19519849,
       201051.59747908, 108605.47091228, 192337.26705261, 160287.88627312,
       197002.87199557, 136215.42508327, 118555.50934592, 179893.61307468,
       455837.74363528, 189209.93476754, 212851.61452146, 291821.65889194,
       165452.2477676 , 125497.29494616, 171633.37735903, 267873.93543589,
       195573.17821891, 208734.05493085, 152754.21714457, 137972.49273979,
       217135.47226125, 136775.43169765, 297775.60638528, 287074.66355278,
       128368.22677645, 225427.85763579, 153805.71065096, 158486.68414818,
       190102.33065401, 320471.39030375, 342894.65495105, 116771.56399056,
       196592.1897677 , 148850.03583906, 176785.60633215, 179936.38857717,
       212035.02064321, 470930.45624736, 290459.3019862 , 103704.08620739,
        98919.00097341, 138095.68824557, 221973.3913239 , 197405.42304639,
       154843.55088682, 115895.37042071, 203495.45591426, 231957.96322884,
       133815.24008961, 275545.22469305,  87989.3058975 , 183827.39544749,
       116970.02970884, 416538.04280857, 117175.97337189, 199821.28598151,
       124220.74114213, 177197.9741289 , 230893.876495  , 147688.27934297,
       178985.93457806, 181764.19915037, 151218.1854865 , 134437.05399304,
       178977.09346447, 308105.5396897 , 151380.22642359,  78326.01110876,
       132065.55227722])

In [38]:
data_unseen['y-hat'] = np.round(predictions,2)
data_unseen['y-hat']

45      274907.31
60      166013.00
83      127526.38
87      171233.20
109     201051.60
          ...
1284    178977.09
1302    308105.54
1308    151380.23
1321     78326.01
1431    132065.55
Name: y-hat, Length: 73, dtype: float64

In [39]:
data_unseen['pct_err'] = (abs(data_unseen['SalePrice'] - data_unseen['y-hat'])) / data_unseen['SalePrice']
data_unseen

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,y-hat,pct_err
45,46,120,RL,61.0,7658,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,2,2010,WD,Normal,319900,274907.31,0.140646
60,61,20,RL,63.0,13072,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,5,2006,New,Partial,158000,166013.00,0.050715
83,84,20,RL,80.0,8892,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,0,7,2007,COD,Normal,126500,127526.38,0.008114
87,88,160,FV,40.0,3951,Pave,Pave,Reg,Lvl,AllPub,...,NaN,NaN,0,6,2009,New,Partial,164500,171233.20,0.040931
109,110,20,RL,105.0,11751,Pave,NaN,IR1,Lvl,AllPub,...,MnPrv,NaN,0,1,2010,COD,Normal,190000,201051.60,0.058166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1284,1285,50,RL,50.0,9638,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,3,2010,WD,Normal,169000,178977.09,0.059036
1302,1303,60,RL,92.0,10120,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,12,2006,WD,Normal,290000,308105.54,0.062433
1308,1309,20,RM,100.0,12000,Pave,NaN,Reg,Lvl,AllPub,...,GdWo,NaN,0,5,2008,WD,Normal,147000,151380.23,0.029797
1321,1322,20,RL,NaN,6627,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,0,7,2008,WD,Normal,72500,78326.01,0.080359
1431,1432,120,RL,NaN,4928,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,0,10,2009,WD,Normal,143750,132065.55,0.081283

In [40]:
outliars_unseen = data_unseen[data_unseen['pct_err'] > 0.15].shape
outliars_unseen

(9, 83)

In [41]:
data_unseen.shape

(73, 83)

In [42]:
# MAE on Outliars 
MAE = outliars_unseen[0]/ data_unseen.shape[0]
MAE

0.1232876712328767

In [43]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [44]:
beta_model = predict_model(model_test,data=df.drop('SalePrice', axis=1))
beta_model

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,prediction_label
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208342.432682
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,171544.166940
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,211520.275387
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,155059.844038
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,276723.970554
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175196.618179
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,204680.176548
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,268569.528587
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,141122.549256
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,151102.221059

In [45]:
beta_model['SalePrice'] = df['SalePrice']
beta_model

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,prediction_label,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2008,WD,Normal,208342.432682,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,5,2007,WD,Normal,171544.166940,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,9,2008,WD,Normal,211520.275387,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2006,WD,Abnorml,155059.844038,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,12,2008,WD,Normal,276723.970554,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,8,2007,WD,Normal,175196.618179,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,NaN,MnPrv,NaN,0,2,2010,WD,Normal,204680.176548,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,268569.528587,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,4,2010,WD,Normal,141122.549256,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2008,WD,Normal,151102.221059,147500

In [46]:
beta_model['pct_err'] = (abs (beta_model['SalePrice'] - beta_model['prediction_label'])) / beta_model['SalePrice']
beta_model

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,prediction_label,SalePrice,pct_err
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,2,2008,WD,Normal,208342.432682,208500,0.000756
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,5,2007,WD,Normal,171544.166940,181500,0.054853
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,0,9,2008,WD,Normal,211520.275387,223500,0.053601
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,0,2,2006,WD,Abnorml,155059.844038,140000,0.107570
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,0,12,2008,WD,Normal,276723.970554,250000,0.106896
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,8,2007,WD,Normal,175196.618179,175000,0.001124
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,MnPrv,NaN,0,2,2010,WD,Normal,204680.176548,210000,0.025332
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,GdPrv,Shed,2500,5,2010,WD,Normal,268569.528587,266500,0.007766
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,4,2010,WD,Normal,141122.549256,142125,0.007053
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,6,2008,WD,Normal,151102.221059,147500,0.024422

In [47]:
beta_model = beta_model.sort_values('pct_err', ascending=False)
beta_model

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,prediction_label,SalePrice,pct_err
632,633,20,RL,85.0,11900,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,4,2009,WD,Family,137390.640489,82500,0.665341
462,463,20,RL,60.0,8281,Pave,NaN,IR1,Lvl,AllPub,...,GdWo,NaN,0,12,2009,WD,Normal,98967.030430,62383,0.586442
968,969,50,RM,50.0,5925,Pave,NaN,Reg,Lvl,AllPub,...,GdWo,NaN,0,5,2009,WD,Abnorml,55197.429899,37900,0.456397
529,530,20,RL,NaN,32668,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,0,3,2007,WD,Alloca,287074.663553,200624,0.430909
30,31,70,C (all),50.0,8500,Pave,Pave,Reg,Lvl,AllPub,...,MnPrv,NaN,0,7,2008,WD,Normal,56653.835935,40000,0.416346
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
698,699,20,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,MnPrv,NaN,0,4,2010,WD,Normal,138518.164580,138500,0.000131
272,273,60,RL,92.0,11764,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,0,4,2010,WD,Normal,290027.815238,290000,0.000096
919,920,20,RL,87.0,11029,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,0,5,2008,WD,Normal,176484.543750,176500,0.000088
902,903,60,RL,63.0,7875,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,7,2006,WD,Normal,179995.896233,180000,0.000023
1074,1075,20,RL,74.0,8556,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,5,2007,WD,Normal,193998.030052,194000,0.000010

In [48]:
beta_model[beta_model['pct_err'] > 0.15].shape

(42, 83)

In [49]:
print(df.shape,'\n', beta_model[beta_model['pct_err']> 0.15].shape)

(1460, 81)
 (42, 83)

In [50]:
print(beta_model[beta_model['pct_err']> 0.15].shape[0]/df.shape[0])

0.028767123287671233